openapi: 3.0.1
info:
  title: WildTenants log models
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths: {}

components:
  schemas:
    CommonLogModel:
      title: Общая модель лога
      description: Общая модель лога для всех микросервисов системы
      type: object
      properties:
        messageTime:
          type: string
        logId:
          type: string
        source:
          type: string
        ub:
          $ref: '#/components/schemas/LogModel'
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorLogModel'

    LogModel:
      title: Модель лога для микросервиса WildTenants
      type: object
      properties:
        requestId:
          type: string
        operation:
          type: string
          enum:
            - create
            - read
            - update
            - delete
            - search
            - init
            - finish
        request:
          $ref: '#/components/schemas/UbLog'
        requestFilter:
          $ref: '#/components/schemas/UbFilterLog'
        response:
          $ref: '#/components/schemas/UbLog'
        responses:
          type: array
          items:
            $ref: '#/components/schemas/UbLog'

    ErrorLogModel:
      title: Модель лога для ошибки
      type: object
      properties:
        message:
          type: string
        field:
          type: string
        code:
          type: string
        level:
          type: string

    UbLog:
      type: object
      description: Модель лога для показания счетчика
      properties:
        id:
          type: string
          description: Идентификатор квитанции
        meterReadings:
          type: array
          items:
            $ref: '#/components/schemas/MeterReading'
        period:
          type: string
          description: Период
        permissions:
          type: array
          uniqueItems: true
          items:
            type: string

    MeterReading:
      type: object
      description: Показания счетчика
      properties:
        name:
          type: string
          description: Наименование счетчика
          enum:
            - electricity
            - coldWater
            - hotWater
        value:
          type: number
          description: Показание счетчика
        volumeForPeriod:
          type: number
          description: Объем за период
        accruedSum:
          type: number
          description: Начисленная сумма
        paidAmount:
          type: number
          description: Оплаченная сумма

    UbFilterLog:
      title: Модель лога фильтра
      properties:
        searchString:
          type: string
        ownerId:
          type: string
